Put contexts dict in <script> and reveal them using JavaScript
coveragepy/coveragepy pull request #1587
Opened 2023-03-16 18:12 UTC by abo-abo

Fixes #1584.
The overall size of the generated HTML files has shrunk from 1.5G to 257M.
The size of the largest file down from 196M down to 9.2M.
All files are manageable now with <1s load time in the browser. And maybe 1s reveal time via JavaScript in case of 5k contexts.

2023-03-17 14:51 UTC, nedbat commented on coverage/html.py
> +        contexts=Counter(c for cline in file_data.lines for c in cline.contexts)
Suprisingly, my linters don't complain about the lack of spaces around the `=` here...

2023-03-17 14:52 UTC, nedbat commented on coverage/html.py
> +            ldata.context_str = ",".join([str(context_codes[c_context]) for c_context in ldata.context_list])
nit: you don't need the list comprehension inside the `join`, you can just remove the square brackets.

2023-03-17 14:53 UTC, nedbat commented on coverage/html.py
> +            di["contexts_json"] = None
Wouldn't it just be easier to use:
```python
file_data["contexts_json"] = None
```
and then not have to create the `di` variable?

2023-03-17 14:54 UTC, nedbat commented on coverage/html.py
> +        if contexts_json == "{}":
It feels a little odd to check for no contexts like this.  Can we use `if not contexts:` instead?

2023-03-17 14:55 UTC, nedbat commented on coverage/htmlfiles/coverage_html.js
Please note that I use four-space indents in .js and .html files.  I recommend an editorconfig plugin for your editor to adjust settings automatically.

2023-03-17 14:57 UTC, nedbat commented on coverage/htmlfiles/coverage_html.js
> +  });
Maybe this code should be inside `pyfile_ready`, since it only applies to those files?

2023-03-17 14:57 UTC, nedbat commented on coverage/htmlfiles/coverage_html.js
> +      span.appendChild(document.createElement("br"));
This creates slightly different HTML than the current code, so the styling needs to be adjusted to keep the right-alignment.

2023-03-17 14:58 UTC, nedbat requested changes
Thanks so much for doing this.  There are other linting errors to address also.

2023-03-17 15:01 UTC, nedbat commented
Now I'm wondering about fancier over-engineered more compact encodings of the contexts, but that can wait (perhaps until never).

2023-03-17 15:50 UTC, abo-abo commented
Hi. Thanks for the review. I've addressed the review comments. Even the CSS one somehow. Please check if it's fine: I'm not a frontend guy so I just googled.

2023-03-17 16:10 UTC, nedbat commented on coverage/htmlfiles/style.css
> +#source p .ctxs { display: block; max-height: 0; overflow-y: hidden; transition: all .2s; padding: 0 .5em; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Ubuntu, Cantarell, "Helv
This file is generated from a .scss file.  You want to add this setting in place of the `span` clause here: https://github.com/nedbat/coveragepy/blob/master/coverage/htmlfiles/style.scss#L625-L628

2023-03-17 16:11 UTC, nedbat commented
I'm surprised you didn't need to update any tests. That tells me that I had no tests of HTML output with contexts!? Yikes.  I can provide one later.

2023-03-17 16:12 UTC, nedbat commented
The test failures are because the CSS file has changed.  I can help get those tests passing once you move the setting to the .scss file.

2023-03-20 15:50 UTC, abo-abo commented
Hi. I've fixed the tests except `tox lint`. That seems to fail unrelated to the PR?

2023-03-20 16:01 UTC, nedbat commented
The lint failures are in your changes in html.py:
```
coverage/html.py:390 C: Line too long (107/100) (line-too-long)
coverage/html.py:13 W: Reimport 'json' (imported line 9) (reimported)
coverage/html.py:13 C: Imports from package json are not grouped (ungrouped-imports)
```
Also, the mypy failure:
```
coverage/html.py:390: error: "LineData" has no attribute "context_str"; maybe "context_list" or "contexts"?  [attr-defined]
```

2023-03-20 20:07 UTC, abo-abo commented
Ah, I see it now. Github actions has helpfully hidden the lint results like this:
```
> tox:lint
... weird exit code...
```
So I had to click on `> tox:lint` to see the lint erorrs. Thanks for pointing this out!

2023-03-21 13:13 UTC, nedbat commented
I added a test to the master branch that should fail here because the context HTML is different.  We can update the gold files on this branch to make them pass.

2023-03-21 15:17 UTC, nedbat commented
To fix the test failures now, you should be able to cd into `tests/gold/html`, and run `make update-gold`.

2023-03-22 16:38 UTC, nedbat approved these changes

2023-03-22 16:42 UTC, merged

2023-04-01 13:09 UTC, nedbat commented
BTW, in b8498bf9 I made the shortcodes more compact. It shaved another 5% off the size of my contextful HTML reports.

2023-04-06 14:38 UTC, nedbat commented
This is now released as part of [coverage 7.2.3](https://pypi.org/project/coverage/7.2.3).