Create Migration notes for for 6.x to 7.x
coveragepy/coveragepy pull request #1610
Opened 2023-04-24 17:57 UTC by paxnovem

Provides migrating versions #1558

2023-04-24 23:01 UTC, nedbat requested changes

2023-04-24 23:01 UTC, nedbat commented on .gitignore
> +.devcontainer/devcontainer.json
Do we need this file? It sounds like something that should be in a global git ignore. I'm not familiar with it.

2023-04-24 23:01 UTC, nedbat commented on doc/migrations.rst
> +
This is doubled.

2023-04-24 23:01 UTC, nedbat commented on doc/migrations.rst
> +--------------------------
Add a blank line, and please make the rules match the length of the titles.

2023-04-24 23:01 UTC, nedbat commented on doc/migrations.rst
> +- The way that wildcards when specifing file paths work in certain cases as changed in 7.0.x:
```suggestion
- The way that wildcards when specifing file paths work in certain cases has changed in 7.0.x:
```

2023-04-24 23:04 UTC, nedbat commented on doc/migrations.rst
> +    to be changed to ``*/tests/*``.
```suggestion
    precise matching difficult. Patterns such as ``*tests/*``
    will need to be changed to ``*/tests/*``.
```

2023-04-24 23:36 UTC, paxnovem commented on .gitignore
> +.devcontainer/devcontainer.json
I added that to prevent my local environment from getting committed. I removed this and locally used `.git/info/exclude` instead.

2023-04-25 15:04 UTC, nedbat commented
I resolved the conflicts and merged it in commit d6e621aa. Thanks!

2023-04-25 15:04 UTC, closed without merging

2023-04-28 10:20 UTC, nedbat commented
This is now released as part of [coverage 7.2.4](https://pypi.org/project/coverage/7.2.4).