Added arm64 job for Travis-CI
coveragepy/coveragepy pull request #908
Opened 2019-12-30 06:11 UTC by ossdev07

Travis-CI has added support for ARM64. Added ARM64 jobs in Travis-CI.

2020-01-31 07:10 UTC, ossdev07 commented
HI @nedbat , Can you please have a look at this PR.

2020-01-31 11:02 UTC, nedbat commented
Help me understand the value here.  Coverage.py doesn't have tricky processor-specific code that I know of.

2020-02-06 15:37 UTC, rhenwood-arm commented
hi @nedbat 
I've been working with @ossdev07 on a downstream project on AArch64 (ARM64) that has coveragepy as a dependency. As you point out, coveragepy is a pure python project with a straightforward Travis-CI build job and that doesn't have a binary release. In this case, there is very little benefit in testing on alternative architectures, and this PR can probably be held in reserve until it is needed.

2020-02-06 16:09 UTC, nedbat commented
@rhenwood-arm Actually, coverage.py has a C extension, so it does compile code.  But I didn't realize that processor differences in that C code were likely enough to warrant the extra builds and time. Do they?

2020-02-06 17:01 UTC, rhenwood-arm requested changes

2020-02-06 17:01 UTC, rhenwood-arm commented on .travis.yml
> +      # Skipping for Arm64, pypy has aarch64 support - but it isn't released yet.
I find this very hard to read with 'arm64' and 'amd64' interspersed. Can the architectures be grouped together to make it more readable?

Also, python 2.7 can be omitted for arm64 as it is EOL.

2020-02-06 18:30 UTC, rhenwood-arm commented
Ah! indeed - I didn't spot ctracer!
Native code provides an opportunity to break on a given platform, so testing is typically valuable. As a more general goal, I am working on figuring out how Arm can support wheels and manylinux2014 activities. So this library is a good example to pursue for me.

I clicked around and I couldn't find the Arm test so I'm unsure what the delay is. @ossdev07 do you have the test duration on AArch64?

2020-02-13 12:36 UTC, ossdev07 commented
Hi @nedbat
Modified PR, added arm64 job for just python3.8 as it has already a lot of existing tests which were taking considerable amount of time. 
I think it's good to have it tested on aarch64 platform as well.

2020-02-17 20:12 UTC, merged

2020-02-17 20:12 UTC, nedbat commented
Thanks!